version: "3.8"

services:
  web:
    build: .
    container_name: web
    command: bash -c "./docker_entrypoints.sh"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - elasticsearch

  pgdb:
    image: postgres
    ports:
      - "5432:5432"
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  
  elasticsearch:
    image: elasticsearch:7.10.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data

volumes:
  pgdata:
  elasticsearch-data-volume:

    