# Generated by Django 3.1.7 on 2021-02-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('isbn13', models.CharField(max_length=40, verbose_name='Isbn13')),
                ('image', models.CharField(max_length=50, verbose_name='Image')),
                ('keyword', models.CharField(max_length=350, verbose_name='Keywords')),
            ],
            options={
                'verbose_name_plural': 'Search Table',
            },
        ),
    ]
